### ISSUE TITLE
How to capture arrow keys?

### ISSUE THREAD

**Issue by specialblend** [leostera/minttea#10]
I see in [example](https://github.com/leostera/minttea/blob/main/examples/views/main.ml#L93) it's matching on `j` or `down` but down arrow key doesn't seem to be working for me. 

Do you know if this is OS- or shell specific? I'm using `zsh` on macOS 14.2

**Comment by leostera** [comment]
Thanks for opening the issue! ✨ The right string would have been "<down>" but strings are both super convenient and terrible at the same time, so I've moved us to variants with some of the common keys as constructors.

This helps enforce the examples to be up to date, but should also help discovering what keys you can match on, and hopefully make it a nicer experience overall 😄 

Hope this helps!
