### ISSUE TITLE
Terminal attributes not reset after termination

### ISSUE THREAD

**Issue by nguermond** [leostera/minttea#14]
I am using minttea 0.0.1 (this is still the case with the latest commit 6a044e7aab4c5451de9e4c96207840873c8472c6) with Ocaml 5.1.1 and I am having the issue that upon termination, the terminal mode is not properly reset. In particular, after successful termination of the examples, the [`Unix.terminal_io`](https://v2.ocaml.org/api/Unix.html#TYPEterminal_io) parameters `c_icanon` and `c_echo` are not set to true, so I cannot see anything when I type something in the terminal after exiting.

Currently I am using the following workaround:

```ocaml 
let termio = (Unix.tcgetattr (Unix.descr_of_in_channel stdin))
let () = Minttea.app ~init ~initial_model ~update ~view () |> Minttea.start;
         Tty.Stdin.shutdown termio
```

I think the following:
 https://github.com/leostera/minttea/blob/6a044e7aab4c5451de9e4c96207840873c8472c6/minttea/io_loop.ml#L40 
should be taking care of this but it doesn't seem to be working.

**Comment by leostera** [comment]
Oh great catch! I think this is happening because the Io_loop process is not actually trapping exits to perform the shutdown, but its only guarding agains the loop function throwing.

Let me have a look 🙏🏼

**Comment by leostera** [comment]
Incoming fix! 🚀 https://github.com/leostera/minttea/commit/397336cbe77b4dd023e629f88fc5ac9a8c82b0ac ensures that during the shutdown sequence of the processes, we always call `Stdin.shutdown termios`. 

Should be available on `main` now for you to try :) I tested using `stty` on my terminal and everything seems in order.

**Comment by nguermond** [comment]
I tested this in the ubuntu terminal and my emacs shell and it works now, thanks!

**Comment by leostera** [comment]
Amazing! Closing now 🙏🏼 Thanks for opening the issue!
