### ISSUE TITLE
Missing Opam package in Leaves dependencies - Colors

### ISSUE THREAD

**Issue by charleslambert** [leostera/minttea#15]
Hey, It seems that the Colors package, which I can see in your github repos, is not  currently a package available for opam. Which causes minttea not to build.

**Comment by leostera** [comment]
Hi @charleslambert 👋🏼 – colors [_just_ got merged into opam](https://github.com/ocaml/opam-repository/pull/24975#event-11320762140) so it should be installable now. Sorry for the trouble! 🙏🏼

**Comment by charleslambert** [comment]
Thanks for update.

**Comment by charleslambert** [comment]
Thanks for quick update!
