### ISSUE TITLE
Make it possible to hide default terminal cursor when Minttea is running

### ISSUE THREAD

**Issue by lessp** [leostera/minttea#17]
Currently the terminal cursor is visible when running Minttea. I think it'd be neat if one was able to hide it.

I could be wrong, but at least Bubbletea has a flag in the renderer, see https://github.com/charmbracelet/bubbletea/blob/master/standard_renderer.go

**Comment by leostera** [comment]
Hi @lessp! 👋🏼 I've added a `Hide_cursor` and `Show_cursor` commands, and amended the text-input example to show how they work. This should be it but feel free to reopen if I missed anything! 🙏🏼
