### ISSUE TITLE
Tutorial in README

### ISSUE THREAD

**Issue by quietlight** [leostera/minttea#21]
The tutorial in the readme fails for me:

```
File "main.ml", line 28, characters 19-22:
28 |   | Event.KeyDown (Key "q" | Escape) -> (model, Command.Quit)
                        ^^^
Error: Unbound constructor Key
```
This happens even when i use the dune file in the basic example, it imports other libraries that the readme tutorial does not.

Also a good idea to clean up confusion with shop.ml/main.ml in README.

Obviously there is a lot to get done and not much time, but I am a beginner (there will be others) and mostly just want a tui that works and is easier to conceptulise than nottui. Mint Tea is great, except it has exactly the same problem as nottui, the example in the readme is broken.

The way I like to learn is to start with a very simple working example, then to go off in my own direction trying to implement other things, step by step.

Kindness and thanks for your hard work.
David

**Comment by quietlight** [comment]
Ok, I see I am using minttea 0.1 from opam, when you have just pushed 0.2. When I refer to the more limited docs in 0.1 it all works. I assume opam will catch up soon.

Thanks for your work, I have something I can work with myself now.

Kindness
David

**Comment by leostera** [comment]
Hi @quietlight – thanks for opening the issue! ✨ 

The current readme reflects what works on the current main, so you'll have to get minttea 0.0.2 or adapt the tutorial a little bit.

I'd suggest that you get 0.0.2 (which is in opam now), that should make your life easier 🙏🏼

**Comment by quietlight** [comment]
Thanks yes, I got v0.0.2 from opam yesterday and the tutorials are working fine for me.

Kindness and good luck.
David
