### ISSUE TITLE
Mint Tea hangs when trying to render a TUI app

### ISSUE THREAD

**Issue by chshersh** [leostera/minttea#34]
I noticed that my Mint Tea app hangs on the start occasionally.

Sometimes the app is snappy but sometimes displays the initial screen and ignores all the future key events (or takes about 20 seconds to process a keyboard event).

When such a problem happens, I see that `strace` spams with errors:

```
clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000}, NULL) = 0
futex(0x55aab30882a8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x55aab503d8b0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x55aab503d8b0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x55aab503d8b0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x55aab503d8b0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x55aab503d8b0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x55aab503d8b0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x55aab503d8b0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x55aab503d8b0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x55aab30882a8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x55aab503d8b0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x55aab503d8b0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x55aab503d8b0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x55aab503d8b0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x55aab503d8b0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x55aab503d8b0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x55aab503d8b0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x55aab503d8b0, FUTEX_WAKE_PRIVATE, 1) = 0
```

I forked minttea and added some logging, and I observed that Mint Tea hangs on receiving and processing Frame events here:

* https://github.com/leostera/minttea/blob/7a64431fb340328d70c45c2a1f009d3fe431b823/minttea/program.ml#L14

You can try to reproduce the problem using the following project:

* https://github.com/chshersh/github-tui/tree/0110a532c2b2c4e943a8cb5616f9a0850394a86f

It uses OCaml 5.1.1 and pinned from GitHub versions of all Mint Tea ecosystem dependencies.

Run the project by executing `dune exec bin/main.exe` and try pressing numbers 1,2,3 or arrows or hjkl or q to quit.

**Expected behaviour:** The TUI app is immediately responsive and rerenders instantly

**Actual behaviour:** The TUI app sometimes hangs and stops responding to input key events

> The error is flaky and is not always reproducible

I'm on Windows 11 and running my project through WSL2 and Ubuntu.

**Comment by Lattay** [comment]
Hi,
I think I observe the same bug when running the basic example with commit 7a64431fb340.

Here are gifs made from the same program [examples/basic/main.ml](https://github.com/leostera/minttea/blob/7a64431fb340328d70c45c2a1f009d3fe431b823/examples/basic/main.ml) and the same tape file [examples/basic/demo.tape](https://github.com/leostera/minttea/blob/7a64431fb340328d70c45c2a1f009d3fe431b823/examples/basic/demo.tape):

![demo_ok](https://github.com/leostera/minttea/assets/24568527/186a0e61-c751-4cf7-b1b7-d52847779c99)
![demo_hang](https://github.com/leostera/minttea/assets/24568527/6fd26fb3-0fdc-4c72-a651-59e28dd63929)

It is not clear to me whether the EAGAIN errors are a problem, as the traces from a good run has a lot of them too.
Here are two traces for a good and a hanging run (the pointers have been renamed to reduce differences between the traces and simplify comparison):

[strace_ok.txt](https://github.com/leostera/minttea/files/14270363/strace_ok.txt)
[strace_hang.txt](https://github.com/leostera/minttea/files/14270365/strace_hang.txt)

I am on Arch Linux running OCaml 5.1.1 with pinned repositories for all the riot ecosystem.

**Comment by chshersh** [comment]
A solution for #46 fixes the problem for me, so I'm happy to close this as a duplicate.
