### ISSUE TITLE
[FR] lipgloss for minttea?

### ISSUE THREAD

**Issue by glyh** [leostera/minttea#51]
I know this better up live in another repo, but is there any plan for a style definition package for minttea? 

There's [lipgloss](https://github.com/charmbracelet/lipgloss) for bubbletea. 

Thanks!

**Comment by leostera** [comment]
Hi @glyh we currently have [Spices](https://github.com/leostera/minttea/tree/main/spices) living in this same repo, which provides tools for defining styles (as the many examples show). 

It is definitely not as feature complete as Lipgloss, but PRs to add features to Spices are super welcome! 🙏🏼 

If its alright with you we can turn this issue into a feature-parity tracker for Lipgloss/Spices?

**Comment by glyh** [comment]
Great.
