### ISSUE TITLE
how to capture backspace key event?

### ISSUE THREAD

**Issue by specialblend** [leostera/minttea#8]
is it possible to capture backspace or delete key? I've tried with:

```ocaml
  let update e state =
    match e with
    | Event.KeyDown "\n" -> (type_enter state, Command.Noop)
    | Event.KeyDown "\b" -> (type_delete state, Command.Noop)
    | Event.KeyDown key -> (type_key state key, Command.Noop)
    | _ -> (state, Command.Noop)
```

awesome library thanks for making it!

**Comment by leostera** [comment]
Hi @specialblend! Thanks for opening the issue. It is! I've just merged a change that should help with this. It is unreleased yet so you will want to pin the package with opam.

You should be able to match `Event.KeyDown "<backspace>"` – in the near future these control characters will be variants (i think) so you will match on `Event.KeyDown Backspace` instead.

Hope this helps!
